first security layer added. and bugfixes that the first security layer created are now resolved :) Oficially : BETA

diff --git a/roles/chat_server/files/app/create_room.sh.j2 b/roles/chat_server/files/app/create_room.sh.j2
--- a/roles/chat_server/files/app/create_room.sh.j2
+++ b/roles/chat_server/files/app/create_room.sh.j2
@@ -5,16 +5,26 @@ ROOM_TYPE=$1
 UUID=$2
 DOMAIN=$3
 
-if [[ "$ROOM_TYPE" != "public" ]] && [[ "$ROOM_TYPE" != "private" ]];then
-  echo "invalid room type"
-  exit 1
-fi
 
-invalid_chars_domain=('~' '`' '#' '$' '&' '*' '(' ')' '\' '|' '[' ']' '{' '}' ';' "'" '<' '>' '/' '?' '!')
+invalid_chars_domain=('~' '`' '#' '$' '&' '*' '(' ')' '\' '|' '[' ']' '{' '}' ';' "'" '<' '>' '/' '?' '!' ' ')
+invalid_chars_general=('~' '`' '#' '$' '&' '*' '(' ')' '\' '|' '[' ']' '{' '}' ';' "'" '<' '>' '/' '?' '!' '.' ' ')
 
-DOMAIN_LENGHT=${{"{"}}#DOMAIN{{"}"}}
+ROOM_TYPE_LENGTH=${{"{"}}#ROOM_TYPE{{"}"}}
 CHAR_NUM=0
-while [[ $CHAR_NUM -lt $DOMAIN_LENGHT ]];do
+while [[ $CHAR_NUM -lt $ROOM_TYPE_LENGTH ]];do
+  CHAR=${ROOM_TYPE:$CHAR_NUM:1}
+  for I_CHAR in "${invalid_chars_general[@]}";do
+    if [[ "$CHAR" == "$I_CHAR" ]];then
+      echo "invalid char $I_CHAR detected in room type"
+      exit 1
+    fi
+  done
+  ((CHAR_NUM++))
+done
+
+DOMAIN_LENGTH=${{"{"}}#DOMAIN{{"}"}}
+CHAR_NUM=0
+while [[ $CHAR_NUM -lt $DOMAIN_LENGTH ]];do
   CHAR=${DOMAIN:$CHAR_NUM:1}
   for I_CHAR in "${invalid_chars_domain[@]}";do
     if [[ "$CHAR" == "$I_CHAR" ]];then
@@ -25,13 +35,11 @@ while [[ $CHAR_NUM -lt $DOMAIN_LENGHT ]];do
   ((CHAR_NUM++))
 done
 
-invalid_chars_uuid=('~' '`' '#' '$' '&' '*' '(' ')' '\' '|' '[' ']' '{' '}' ';' "'" '<' '>' '/' '?' '!' '.')
-
-UUID_LENGHT=${{"{"}}#UUID{{"}"}}
+UUID_LENGTH=${{"{"}}#UUID{{"}"}}
 CHAR_NUM=0
-while [[ $CHAR_NUM -lt $UUID_LENGHT ]];do
+while [[ $CHAR_NUM -lt $UUID_LENGTH ]];do
   CHAR=${UUID:$CHAR_NUM:1}
-  for I_CHAR in "${invalid_chars_uuid[@]}";do
+  for I_CHAR in "${invalid_chars_general[@]}";do
     if [[ "$CHAR" == "$I_CHAR" ]];then
       echo "invalid char $I_CHAR detected in uuid"
       exit 1
@@ -39,6 +47,30 @@ while [[ $CHAR_NUM -lt $UUID_LENGHT ]];do
   done
   ((CHAR_NUM++))
 done
+
+if [[ "$ROOM_TYPE" != "public" ]] && [[ "$ROOM_TYPE" != "private" ]];then
+  echo "invalid room type"
+  exit 1
+fi
+
+if egrep '^[0-9a-f]{8}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{4}-[0-9a-f]{12}$' <<< $UUID;then
+  echo "uuid valid"
+else
+  echo "uuid invalid"
+  exit 1
+fi
+
+if egrep '^([^.]{1,250}\.)?([^.]{1,250}\.)?[^.]{1,250}\.[^.]{1,250}$' <<< $DOMAIN;then
+  echo "domain valid"
+else
+  echo "invalid domain"
+  exit 1
+fi
+
+if [[ $DOMAIN_LENGTH -gt 250 ]];then 
+  echo "invalid domain"
+  exit 1
+fi
 
 
 #######################################
@@ -123,8 +155,8 @@ chmod 0440 /var/www/${DOMAIN}/app/rooms/${UUID}/chat.html
 chmod 0640 /var/www/${DOMAIN}/app/rooms/${UUID}/version.txt
 chmod 0440 /var/www/${DOMAIN}/app/rooms/${UUID}/tc.ico
 chmod 0640 /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html
-CONV_LENGHT=$(cat /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html | wc -l)
-HTML_BODY=$(($CONV_LENGHT-2))
+CONV_LENGTH=$(cat /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html | wc -l)
+HTML_BODY=$(($CONV_LENGTH-2))
 sed "${HTML_BODY}i<div class=\"speech\" <b>welcome to room ${UUID} on ${DOMAIN}</b></div>" /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html > /var/www/${DOMAIN}/app/rooms/${UUID}/temp.html
 cat /var/www/${DOMAIN}/app/rooms/${UUID}/temp.html > /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html
 rm /var/www/${DOMAIN}/app/rooms/${UUID}/temp.html
@@ -225,8 +257,8 @@ chmod 0440 /var/www/${DOMAIN}/app/rooms/${UUID}/icons/*
 chmod 0440 /var/www/${DOMAIN}/app/rooms/${UUID}/chat.html
 chmod 0440 /var/www/${DOMAIN}/app/rooms/${UUID}/tc.ico
 chmod 0640 /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html
-CONV_LENGHT=$(cat /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html | wc -l)
-HTML_BODY=$(($CONV_LENGHT-2))
+CONV_LENGTH=$(cat /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html | wc -l)
+HTML_BODY=$(($CONV_LENGTH-2))
 sed "${HTML_BODY}i<div class=\"speech\" <b>welcome to room ${UUID} on ${DOMAIN}</b></div>" /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html > /var/www/${DOMAIN}/app/rooms/${UUID}/temp.html
 cat /var/www/${DOMAIN}/app/rooms/${UUID}/temp.html > /var/www/${DOMAIN}/app/rooms/${UUID}/conversation.html
 rm cat /var/www/${DOMAIN}/app/rooms/${UUID}/temp.html
@@ -400,8 +432,8 @@ ln -s /var/www/${DOMAIN}/app/rooms/conversation.html /var/www/${DOMAIN}/html/con
 ln -s /var/www/${DOMAIN}/app/rooms/html_top /var/www/${DOMAIN}/html/html_top
 ln -s /var/www/${DOMAIN}/app/rooms/messages /var/www/${DOMAIN}/html/messages
 ln -s /var/www/${DOMAIN}/app/rooms/html_bottom /var/www/${DOMAIN}/html/html_bottom
-CONV_LENGHT=$(cat /var/www/${DOMAIN}/app/rooms/conversation.html | wc -l)
-HTML_BODY=$(($CONV_LENGHT-2))
+CONV_LENGTH=$(cat /var/www/${DOMAIN}/app/rooms/conversation.html | wc -l)
+HTML_BODY=$(($CONV_LENGTH-2))
 sed "${HTML_BODY}i<div class=\"speech\" <b>welcome to room on ${DOMAIN}</b></div>" /var/www/${DOMAIN}/app/rooms/conversation.html > /var/www/${DOMAIN}/app/rooms/temp.html
 cat /var/www/${DOMAIN}/app/rooms/temp.html > /var/www/${DOMAIN}/app/rooms/conversation.html
 rm /var/www/${DOMAIN}/app/rooms/temp.html
@@ -575,8 +607,8 @@ ln -s /var/www/${DOMAIN}/app/rooms/conversation.html /var/www/${DOMAIN}/html/con
 ln -s /var/www/${DOMAIN}/app/rooms/html_top /var/www/${DOMAIN}/html/html_top
 ln -s /var/www/${DOMAIN}/app/rooms/messages /var/www/${DOMAIN}/html/messages
 ln -s /var/www/${DOMAIN}/app/rooms/html_bottom /var/www/${DOMAIN}/html/html_bottom
-CONV_LENGHT=$(cat /var/www/${DOMAIN}/app/rooms/conversation.html | wc -l)
-HTML_BODY=$(($CONV_LENGHT-2))
+CONV_LENGTH=$(cat /var/www/${DOMAIN}/app/rooms/conversation.html | wc -l)
+HTML_BODY=$(($CONV_LENGTH-2))
 sed "${HTML_BODY}i<div class=\"speech\" <b>welcome to room on ${DOMAIN}</b></div>" /var/www/${DOMAIN}/app/rooms/conversation.html > /var/www/${DOMAIN}/app/rooms/temp.html
 cat /var/www/${DOMAIN}/app/rooms/temp.html > /var/www/${DOMAIN}/app/rooms/conversation.html
 rm /var/www/${DOMAIN}/app/rooms/temp.html
diff --git a/roles/chat_server/files/app/destroy_room.sh.j2 b/roles/chat_server/files/app/destroy_room.sh.j2
--- a/roles/chat_server/files/app/destroy_room.sh.j2
+++ b/roles/chat_server/files/app/destroy_room.sh.j2
@@ -5,13 +5,15 @@ USERNAME=$1
 UUID=$2
 DOMAIN=$3
 
-invalid_chars_user=('~' '`' '#' '$' '&' '*' '(' ')' '\' '|' '[' ']' '{' '}' ';' "'" '<' '>' '/' '?' '!' '.')
 
-USERNAME_LENGHT=${{"{"}}#USERNAME{{"}"}}
+invalid_chars_domain=('~' '`' '#' '$' '&' '*' '(' ')' '\' '|' '[' ']' '{' '}' ';' "'" '<' '>' '/' '?' '!')
+invalid_chars_general=('~' '`' '#' '$' '&' '*' '(' ')' '\' '|' '[' ']' '{' '}' ';' "'" '<' '>' '/' '?' '!' '.')
+
+USERNAME_LENGTH=${{"{"}}#USERNAME{{"}"}}
 CHAR_NUM=0
-while [[ $CHAR_NUM -lt $USERNAME_LENGHT ]];do
+while [[ $CHAR_NUM -lt $USERNAME_LENGTH ]];do
   CHAR=${USERNAME:$CHAR_NUM:1}
-  for I_CHAR in "${invalid_chars_user[@]}";do
+  for I_CHAR in "${invalid_chars_general[@]}";do
     if [[ "$CHAR" == "$I_CHAR" ]];then
       echo "invalid char $I_CHAR detected in username"
       exit 1
@@ -20,11 +22,9 @@ while [[ $CHAR_NUM -lt $USERNAME_LENGHT ]];do
   ((CHAR_NUM++))
 done
 
-invalid_chars_domain=('~' '`' '#' '$' '&' '*' '(' ')' '\' '|' '[' ']' '{' '}' ';' "'" '<' '>' '/' '?' '!')
-
-DOMAIN_LENGHT=${{"{"}}#DOMAIN{{"}"}}
+DOMAIN_LENGTH=${{"{"}}#DOMAIN{{"}"}}
 CHAR_NUM=0
-while [[ $CHAR_NUM -lt $DOMAIN_LENGHT ]];do
+while [[ $CHAR_NUM -lt $DOMAIN_LENGTH ]];do
   CHAR=${DOMAIN:$CHAR_NUM:1}
   for I_CHAR in "${invalid_chars_domain[@]}";do
     if [[ "$CHAR" == "$I_CHAR" ]];then
@@ -35,16 +35,32 @@ while [[ $CHAR_NUM -lt $DOMAIN_LENGHT ]];do
   ((CHAR_NUM++))
 done
 
+if egrep '^([^.]{1,250}\.)?([^.]{1,250}\.)?[^.]{1,250}\.[^.]{1,250}$' <<< $DOMAIN;then
+  echo "domain valid"
+else
+  echo "invalid domain"
+  exit 1
+fi
+
+if [[ $DOMAIN_LENGTH -gt 250 ]];then
+  echo "invalid domain"
+  exit 1
+fi
+
+if [[ $USERNAME_LENGTH -gt 100 ]];then
+  echo "invalid username"
+  exit 1
+fi  
+
 
 {% if multirooms == True %}
 
-invalid_chars_uuid=('~' '`' '#' '$' '&' '*' '(' ')' '\' '|' '[' ']' '{' '}' ';' "'" '<' '>' '/' '?' '!' '.')
 
-UUID_LENGHT=${{"{"}}#UUID{{"}"}}
+UUID_LENGTH=${{"{"}}#UUID{{"}"}}
 CHAR_NUM=0
-while [[ $CHAR_NUM -lt $UUID_LENGHT ]];do
+while [[ $CHAR_NUM -lt $UUID_LENGTH ]];do
   CHAR=${UUID:$CHAR_NUM:1}
-  for I_CHAR in "${invalid_chars_uuid[@]}";do
+  for I_CHAR in "${invalid_chars_general[@]}";do
     if [[ "$CHAR" == "$I_CHAR" ]];then
       echo "invalid char $I_CHAR detected in uuid"
       exit 1
@@ -52,6 +68,12 @@ while [[ $CHAR_NUM -lt $UUID_LENGHT ]];do
   done
   ((CHAR_NUM++))
 done
+
+if [[ $(egrep '^[0-9a-f]{8}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{4}-[0-9a-f]{12}$' <<< $UUID) -ne 0 ]];then
+  echo "invalid uuid"
+  exit 1
+fi
+
 
 {% endif %}
 
